<h1>Edit State</h1>

<?php

 $title = 'Editing of state';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

$form = $this->form;
$form->setAttribute('action', $this->url(
     'state',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();