<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}

 $title = 'Editing of state';
 $this->headTitle($title);
 ?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
 <?php

$form = $this->form;
$form->setAttribute('action', $this->url(
     'state',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ))->setAttribute('class', 'form-horizontal');
 
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 printFormGroup($this->formRow($form->get('name')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formSubmit($form->get('submit')
         ->setAttribute('class', 'form-control')
         ->setAttribute('class', 'btn btn-warning')));
 echo $this->form()->closeTag();