<?php $title='States of cases';?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<p><span class="label label-success"><a href="<?php echo $this->url().'add'; ?>">Add new state</a></span></p>
<table class="table table-hover table-striped">
    <tr class="success">
        <td>Name</td>
        <td>Moderation</td>
    </tr>
<?php
    foreach($state as $item) {
        echo "
        <tr>
            <td>".$item->name."</td>";
?>
            <td>
                <a href="<?php echo $this->url('state', array('action'=>'edit', 'id' => $item->id));?>">Edit</a>
                <a href="<?php echo $this->url('state', array('action'=>'delete', 'id' => $item->id));?>">Remove</a>
            </td>
        </tr>
<?php        
    }
?>
</table>