<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CR'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/cr.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Codereview<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                          <li><a href="<?php echo $this->url('home').'codereview/findByUser' ?>"><?php echo $this->translate('Find by User') ?></a></li>
                          <li><a href="<?php echo $this->url('home').'codereview/findByTicket' ?>"><?php echo $this->translate('Find by ticket') ?></a></li>
                          <li class="divider"></li>
                          <li><a href="#">Statistic</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Graphs</a></li>
                        </ul>
                      </li>
                        <li ><a href="<?php echo $this->url('schedule') ?>"><?php echo $this->translate('Schedule') ?></a></li>
                        <li ><a href="<?php echo $this->url('state') ?>"><?php echo $this->translate('State') ?></a></li>
                        <li ><a href="<?php echo $this->url('usergroups') ?>"><?php echo $this->translate('Usergroups') ?></a></li>
                        <li ><a href="<?php echo $this->url('users') ?>"><?php echo $this->translate('Users') ?></a></li>
                        <li >
                        <?php 
                            if (isset($_SESSION['currentUser'])) {
                                echo '<span class="label label-default">Hello '.$_SESSION['currentUser']->ldap.'</span>'
                                    .'<p class="label label-warning"><a href='.$this->url('home').'auth/logout'.'>'.$this->translate('Logout').'</a></p>';
                                
                            } else {
                                echo "<a href=".$this->url('home').'auth/login'.">".$this->translate('Login')."</a>";
                            }
                        ?>
                        </li>
                        <?php
                        if (!isset($_SESSION['currentUser'])) { 
                        ?>
                        <li class=""><a href="<?php echo $this->url('home').'users/add'?>"><?php echo $this->translate('Register');?></a></li>
                        <?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
