<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}
 $title = 'Add new codereview';
 $this->headTitle($title);
 ?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
 <?php
        date_default_timezone_set('Europe/Helsinki');
        $currentDate = date("m-d-Y H:i");
 
$form->setAttribute('action', $this->url('codereview', array('action' => 'add')))
        ->setAttribute('class', 'form-horizontal');
 $form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
printFormGroup($this->formRow($form->get('creationdate')
        ->setAttribute('value', $currentDate)));
printFormGroup($this->formRow($form->get('changeset')));
printFormGroup($this->formRow($form->get('jiraticket')));
printFormGroup($this->formRow($form->get('authorcomments')));
printFormGroup($this->formRow($form->get('reviewercomments')));
printFormGroup($this->formRow($form->get('stateid')));
printFormGroup($this->formRow($form->get('authorid')));
printFormGroup($this->formRow($form->get('reviewerid')));
printFormGroup($this->formRow($form->get('submit')));
echo $this->form()->closeTag();
