<?php
$title = 'Delete codereview';
$this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete row from codereview with JIRA ticket: <span class="label label-info">
    <?php echo $this->escapeHtml($codereview->jiraticket); ?></span> and changeset: <span class="label label-info">
    <?php echo $this->escapeHtml($codereview->changeset); ?></span>?
 </p>
 <?php
 $url = $this->url('codereview', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $codereview->id; ?>" />
     <input type="submit" name="del" value="Yes" class="btn btn-danger"/>
     <input type="submit" name="del" value="No" class="btn btn-primary"/>
 </div>
 </form>