<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}

 $title = 'Edit new codereview';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'codereview',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
))
->setAttribute('class','form-horizontal');
 $form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('states'));exit;
printFormGroup($this->formRow($form->get('creationdate')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('changeset')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('jiraticket')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('authorcomments')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('reviewercomments')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('stateid')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('authorid')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('reviewerid')
        ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('states')
            ->setAttribute('class', 'form-control')));
echo $this->formSubmit($form->get('submit')
        ->setAttribute('class', 'btn btn-warning'));
echo $this->form()->closeTag();
?>