<?php $title = 'Find by user';?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<?php

    function printFormGroup($row = 'null'){
        echo '<div class="form-group"><div class="col-sm-10">'.$row.'</div></div>';
    }
    function commentIsPresent($comment = '') {
        return $comment == '';
    }
    $this->headTitle($this->escapeHtml($title));?>
    <div class="panel panel-info">
        <div class="panel-heading">Search here</div>
        <div class="panel-body"> 
            <?php
            $form->setAttribute('action', $this->url('codereview', array('action' => 'findByUser')))
                    ->setAttribute('class', 'form-inline');
            $form->prepare();
            echo $this->form()->openTag($form);
            printFormGroup($this->formRow($form->get('authorid')));
            printFormGroup($this->formRow($form->get('startdate')));
            printFormGroup($this->formRow($form->get('enddate')));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
<?php
if (isset($codereviews) && count($codereviews) != 0) { ?>
<div class="panel panel-default">
    <div class="panel-heading">Searching result(s)</div>
    <div class="panel-body">
    <table class="table table-hover table-striped">
        <thead>
        <tr class="success">
            <th>Creating date</th>
            <th>Changeset</th>
            <th>JIRA ticket</th>
            <th>Author's comments</th>
            <th>Reviewer's comments</th>
            <th>State</th>
            <th>Author</th>
            <th>Reviewer</th>
        </tr>
        </thead>
    
<?php foreach ($codereviews as $codereview) {
    echo "
        <tr>
        <td>{$codereview['creationdate']}</td>
        <td><a href=".$codereview['changeset']." target='_blank'>{$codereview['changeset']}</a></td>
        <td><a href=".$codereview['jiraticket']." target='_blank'>{$codereview['jiraticket']}</a></td>
        <td>";
        if (commentIsPresent($codereview['authorcomments'])) {
            echo "<button type='button' class='btn btn-default' data-container='body' disabled='disabled' data-toggle='popover' data-placement='top' 
        data-content='{$codereview['authorcomments']}'>Nothing to read</button></td>";
        } else {
            echo "<button type='button' class='btn btn-default btn-info' data-container='body' data-toggle='popover' data-placement='top' 
        data-content='{$codereview['authorcomments']}'>Read me</button></td>";
        }
        echo "<td>";
        if (commentIsPresent($codereview['reviewercomments'])) {
            echo "<button type='button' class='btn btn-default' data-container='body' disabled='disabled' data-toggle='popover' data-placement='bottom' 
        data-content='{$codereview['reviewercomments']}'>Nothing to read</button>";
        } else {
            echo "<button type='button' class='btn btn-default btn-info' data-container='body' data-toggle='popover' data-placement='bottom' 
        data-content='{$codereview['reviewercomments']}'>Read me</button>";
        };
        echo "</td>
    <td class='state'>{$codereview['state']}</td>
    <td>{$codereview['author']}</td>
    <td>{$codereview['reviewer']}</td>
        </tr>";
    } ?>
        </table>
    </div>
</div>   

<?php } else if ($post) { ?>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  Oops...it seems like there is no data to display
</div>
<?php } ?>
