<?php $title = 'Codereview';?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<p><span class="label label-success"><a href="<?php echo $this->url().'add'; ?>">Add changeset</a></span></p>
<p><blockquote><?php echo $message; ?></blockquote></p>
<?php
    $this->headTitle($this->escapeHtml($title));
?>

<table class="table table-hover table-striped">
    <tr class="success">
        <th>Creating date</th>
        <th>Changeset</th>
        <th>JIRA ticket</th>
        <th>Author's comments</th>
        <th>Reviewer's comments</th>
        <th>State</th>
        <th>Author</th>
        <th>Reviewer</th>
        <th>Moderation</th>
    </tr>
<?php
foreach ($codereviews as $codereview) {
    echo "
    <tr>
    <td>{$codereview['creationdate']}</td>
        <td><a href=".$codereview['changeset']." target='_blank'>{$codereview['changeset']}</a></td>
        <td><a href=".$codereview['jiraticket']." target='_blank'>{$codereview['jiraticket']}</a></td>
       <td>{$codereview['authorcomments']}</td>
       <td>{$codereview['reviewercomments']}</td>
       <td>{$codereview['state']}</td>
       <td>{$codereview['reviewer']}</td>
       <td>{$codereview['author']}</td>
       <td><a href=".$this->url('codereview', array('action'=>'edit', 'id' => $codereview['id'])).">Edit</a>
           <a href=".$this->url('codereview', array('action'=>'delete', 'id' => $codereview['id'])).">Delete</a>
       </td>
    </tr>";
}
?>
</table>
