<h1>Edit State</h1>

<?php

 $title = 'Editing of users';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

$form = $this->form;
$form->setAttribute('action', $this->url(
     'users',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('ldap'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('password'));
 echo $this->formRow($form->get('groupid'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();