<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}

 $title = 'Editing of users';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

$form = $this->form;
$form->setAttribute('action', $this->url(
     'users',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ))
->setAttribute('class', 'form-horizontal');
 
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 printFormGroup($this->formRow($form->get('ldap')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formRow($form->get('email')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formRow($form->get('password')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formRow($form->get('groupid')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formSubmit($form->get('submit')
         ->setAttribute('class', 'btn btn-warning')));
 echo $this->form()->closeTag();