<h1>Index of State</h1>

<table class="table table-hover table-striped">
    <tr class="success">
        <td>LDAP</td>
        <td>Email</td>
        <td>Group</td>
        <td>Moderation</td>
    </tr>
<?php
    
    foreach($users as $item) {
        var_dump($users);exit;
        echo "
        <tr>
            <td>".$item->ldap.' = '.$item->id."</td>
            <td>".$item->email."</td>
            <td>".$item->name.$item->groupid."</td>";
?>
            <td>
                <a href="<?php echo $this->url('users', array('action'=>'edit', 'id' => $item->id));?>">Edit</a>
                <a href="<?php echo $this->url('users', array('action'=>'delete', 'id' => $item->id));?>">Remove</a>
            </td>
        </tr>
<?php        
    }
?>
</table>