<?php $title = 'Existed users'; ?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<p><span class="label label-success"><a href="<?php echo $this->url().'add'; ?>">Add new user</a></span></p>
<table class="table table-hover table-striped">
    <tr class="success">
        <td>LDAP</td>
        <td>Email</td>
        <td>Group</td>
        <td>Moderation</td>
    </tr>
<?php
    
    foreach($users as $item) {
        echo "
        <tr>
            <td>".$item['ldap']."</td>
            <td>".$item['email']."</td>
            <td>".$item['name']."</td>";
?>
            <td>
                <a href="<?php echo $this->url('users', array('action'=>'edit', 'id' => $item['id']));?>">Edit</a>
                <a href="<?php echo $this->url('users', array('action'=>'delete', 'id' => $item['id']));?>">Remove</a>
            </td>
        </tr>
<?php        
    }
?>
</table>