<?php $title = 'Reset password for user';?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}

$this->headTitle($this->escapeHtml($title)); ?>
<div class="alert alert-danger fade in" role="alert">
    <button class="close" data-dismiss="alert" type="button">
        <span aria-hidden="true">×</span>
        <span class="sr-only">Close</span>
    </button>
    <strong>This action will reset users' password. Be aware!</strong>
</div>
<?php
    if($this->form->temporaryPassword != '') { ?>
<div class="alert alert-info fade in" role="alert">
    <button class="close" data-dismiss="alert" type="button">
        <span aria-hidden="true">×</span>
        <span class="sr-only">Close</span>
    </button>
    <strong><?php echo $this->form->temporaryPassword;?></strong>
</div>
<?php 
    };
?>
<?php
$form->setAttribute('action', $this->url('users', array('action' => 'resetPassword')))
        ->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
printFormGroup($this->formRow($form->get('userid')));
echo $this->formSubmit($form->get('submit')
        ->setAttribute('class', 'btn btn-danger'));
echo $this->form()->closeTag();

?>