<?php if ($this->pageCount): ?>
        <ul class="pagination">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->first, FALSE, TRUE)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->previous, FALSE, TRUE)); ?>">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url($this->route, array('page' => $page, FALSE, TRUE)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array('page' => $this->next, FALSE, TRUE)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($this->route, array( 'page' => $this->last, FALSE, TRUE)); ?>">&raquo;</a></li>
        </ul>
<?php endif; ?>