<?php

function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}

 $title = 'Add new schedule';
 $this->headTitle($title);
 $form->setAttribute('action', $this->url('schedule', array('action' => 'add')))
         ->setAttribute('class', 'form-horizontal');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
printFormGroup($this->formRow($form->get('reviewer')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('datetimebegin')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('datetimeend')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formSubmit($form->get('submit')
         ->setAttribute('class', 'btn btn-success')));
 echo $this->form()->closeTag();