<h1>Delete Schedule</h1>
<?php
$title = 'Delete schedule';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete schedule of
    '<?php echo $this->escapeHtml($schedule->Reviewer); ?>' start time of which is
    '<?php echo $this->escapeHtml($schedule->DateTimeBegin)." and end time is ".$this->escapeHtml($schedule->DateTimeEnd); ?>'?
</p>
<?php
$url = $this->url('schedule', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $schedule->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>