<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}
 $title = 'Editing of schedule';
 $this->headTitle($title);
 ?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
 <?php

 $form->setAttribute('action', $this->url('schedule', array('action' => 'edit', 'id' => $id)))
         ->setAttribute('class', 'form-horizontal');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
// echo $this->formRow($form->get('users'));
printFormGroup($this->formRow($form->get('Reviewer')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('traineebackupid')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('replacementreviewerid')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('originalreviewerid')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('designreviewerid')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('designtraineereviewerid')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('dateofschedule')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formRow($form->get('timereference')
         ->setAttribute('class', 'form-control')));
printFormGroup($this->formSubmit($form->get('submit')
         ->setAttribute('class', 'btn btn-success')));
 echo $this->form()->closeTag();