<?php
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}
 $title = 'Authorize';
 $this->headTitle($title);
 ?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
 <?php
 $form->setAttribute('action', $this->url('auth', array('action' => 'login')))
         ->setAttribute('class', 'form-horizontal');
 $form->prepare();
if (isset($form->customErrMessage) && $form->customErrMessage != '') { ?>
    <div class="alert alert-danger" role="alert">
        <?php echo $form->customErrMessage ?>
    </div>
<?php }
 echo $this->form()->openTag($form);
 printFormGroup($this->formRow($form->get('ldap')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formRow($form->get('password')
         ->setAttribute('class', 'form-control')));
 printFormGroup($this->formSubmit($form->get('submit')
         ->setAttribute('class', 'btn btn-success')));
 echo $this->form()->closeTag();
 
 if (isset($errorMessage)) {
     echo "$errorMessage";
 }