<?php
$title = 'Add new usergroups';
$this->headTitle($title);
function printFormGroup($row = 'null'){
    echo '<div class="form-group">
    <div class="col-sm-10">';
    echo $row;
    echo '</div>
  </div>';
}
?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<?php
$form->setAttribute('action', $this->url('usergroups', array('action' => 'add')))
    ->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
printFormGroup($this->formRow($form->get('name')));
printFormGroup($this->formSubmit($form->get('submit')));
echo $this->form()->closeTag();