<h1>Delete State</h1>
<?php
$title = 'Delete usergroups';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete usergroups named 
    '<?php echo $this->escapeHtml($usergroups->name); ?>
</p>
<?php
$url = $this->url('usergroups', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $usergroups->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>