<?php
$title = 'All usergroups that exist';
$this->headTitle($title);
?>
<h1 class="text-right" ><small><?php echo $this->escapeHtml($title); ?></small></h1>
<p><span class="label label-success"><a href="<?php echo $this->url().'add'; ?>">Add new group of users</a></span></p>
<table class="table table-hover table-striped">
    <tr class="success">
        <td>Name</td>
        <td>Moderation</td>
    </tr>
<?php
    foreach($usergroups as $item) {
        echo "
        <tr>
            <td>".$item['name']."</td>";
?>
            <td>
                <a class='glyphicon glyphicon-pencil' href="<?php echo $this->url('usergroups', array('action'=>'edit', 'id' => $item['id']));?>"></a>
                <a class='glyphicon glyphicon-remove' href="<?php echo $this->url('usergroups', array('action'=>'delete', 'id' => $item['id']));?>"></a>
            </td>
        </tr>
<?php        
    }
?>
</table>