<h1>Delete Backup</h1>
<?php
$title = 'Delete backup';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete backup of
    '<?php echo $this->escapeHtml($backup->Reviewer); ?>' start time of which is
    '<?php echo $this->escapeHtml($backup->DateTimeBegin)." and end time is ".$this->escapeHtml($backup->DateTimeEnd); ?>'?
</p>
<?php
$url = $this->url('backup', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $backup->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>